### ISSUE TITLE
Support gRPC 1.25.0

### ISSUE THREAD

**Issue by ericbottard** [spring-projects-experimental/spring-graal-native#24]
On this riff [subproject](https://github.com/projectriff/streaming-processor), we realized that native image generation did not work with gRPC 1.25.0.
It does work with 1.24.1 though.

Here is a log of the compilation error: https://github.com/projectriff/streaming-processor/runs/324831191#step:5:378

**Comment by sdeleuze** [comment]
I am not sure we should do something specific in that project, but maybe we can initiate something like a wiki page to track the status of the 3rd party dependencies with a link to the related issue (there is already one for GRPC)

@aclement Any thoughts?

**Comment by aclement** [comment]
How would that overlap with the intent of the graal team to have a site that shows that kind of info (who/what is compatible)? I'd much rather it was centralized under graal itself. We could create one in our project but how quickly will it turn into a maintenance burden.  We'd have to be careful scoping what it would cover if we were maintaining it. Just my 2c.

**Comment by sbrannen** [comment]
We actually discussed similar ideas at the GraalVM community workshop.

The basic idea was that the GraalVM team would try to organize something for the community, potentially an open wiki page and potentially some kind of bot that crawls Maven Central to track artifacts that include GraalVM metadata files.

So, if something is started in _this_ project, I agree that it should be very minimal with the intent to hand it over to the GraalVM community/team.

**Comment by sdeleuze** [comment]
I guess we have enough to do on other topics, so it is probably better to close this issue and wait for the native image compliance catalog that should be indeed initiated by GraalVM team, and the related guidelines and hopefully impact on each library support.
